# Generated by Django 4.0.3 on 2023-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
