# Generated by Django 4.0.3 on 2023-04-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_discord_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushNotificationSubscriptionObjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=2000)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
