# Generated by Django 4.0.3 on 2023-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userpushnotificationsubscriptionobjects_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserPushNotificationSubscriptionObjects',
        ),
    ]
