# Generated by Django 5.1.1 on 2024-11-01 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0008_link_delete_userlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
    ]
