# Generated by Django 5.2.6 on 2025-10-26 02:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_phone_type_id_phonetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=100), verbose_name='Name'),
        ),
    ]
