# Generated by Django 5.2.12 on 2026-06-20 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_ver',
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(blank=True, max_length=500, null=True)),
                ('img_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('img_approved', models.BooleanField(default=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
