# Generated by Django 4.2 on 2023-06-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_id',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='q_opt_id',
            new_name='question_opt_id',
        ),
    ]
