# Generated by Django 4.2 on 2023-07-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_rename_subtype_formsubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubtype',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
