# Generated by Django 4.2 on 2024-02-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_rename_question_questionaggregate_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaggregate',
            name='active',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
