# Generated by Django 5.1.1 on 2024-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_historicalresponse_archive_ind_response_archive_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='table_col_width',
            field=models.CharField(default='100px', max_length=255),
            preserve_default=False,
        ),
    ]
