# Generated by Django 5.1.1 on 2025-01-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_questionanswer_question_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionflow',
            name='single_run',
            field=models.BooleanField(default=False),
        ),
    ]
