# Generated by Django 5.1.1 on 2025-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_questionflow_single_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionConditionType',
            fields=[
                ('question_condition_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question_condition_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='questioncondition',
            old_name='condition',
            new_name='value',
        ),
    ]
