# Generated by Django 5.1.1 on 2025-01-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_questionconditiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncondition',
            name='question_condition_typ',
            field=models.ForeignKey(default='equal', on_delete=django.db.models.deletion.PROTECT, to='form.questionconditiontype'),
            preserve_default=False,
        ),
    ]
