# Generated by Django 5.1.5 on 2025-01-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_questionflow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='QuestionFlowAnswer',
            new_name='FlowAnswer',
        ),
        migrations.AlterField(
            model_name='flowcondition',
            name='flow_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_flow_from', to='form.flow'),
        ),
        migrations.AlterField(
            model_name='flowcondition',
            name='flow_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_flow_to', to='form.flow'),
        ),
    ]
