# Generated by Django 5.1.5 on 2025-01-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_rename_question_answer_flowanswer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='id',
        ),
    ]
