# Generated by Django 5.1.5 on 2025-01-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_rename_question_id_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='svg',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
