# Generated by Django 5.1.5 on 2025-01-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_rename_question_id_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='icon_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='value_multiplier',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
