# Generated by Django 5.1.5 on 2025-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_question_height_question_icon_question_icon_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='svg',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
