# Generated by Django 5.1.5 on 2025-01-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_question_svg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionFlow',
            new_name='FlowQuestion',
        ),
    ]
