# Generated by Django 5.1.5 on 2025-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_graph_scale_graphquestion_question_aggregate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='scale',
            new_name='scale_x',
        ),
        migrations.RemoveField(
            model_name='graphquestiontype',
            name='question_typ',
        ),
        migrations.AddField(
            model_name='graph',
            name='scale_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
