# Generated by Django 5.1.5 on 2025-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0049_graphbin_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphcategory',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
