# Generated by Django 5.1.6 on 2025-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0052_rename_required_graph_question_typ_graphtype_requires_graph_question_typs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaggregate',
            old_name='field_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='questionaggregate',
            name='horizontal',
            field=models.BooleanField(default=True),
        ),
    ]
