# Generated by Django 5.1.5 on 2025-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0058_remove_questionaggregate_question_condition_typ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaggregatequestion',
            name='condition_value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
