# Generated by Django 5.1.5 on 2025-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0059_questionaggregatequestion_condition_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaggregatequestion',
            name='use_answer_time',
            field=models.BooleanField(default=False),
        ),
    ]
