# Generated by Django 3.0.6 on 2020-05-18 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authAPI', '0003_auto_20200515_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='location',
            new_name='method',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='controller',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
