# Generated by Django 5.2.6 on 2025-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_historicalmeeting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
