# Generated by Django 5.2.6 on 2025-10-25 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_approved_historicalattendance_approved'),
        ('scouting', '0070_season_game_season_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='season',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='scouting.season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='season',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scouting.season'),
        ),
    ]
