# Generated by Django 5.2.6 on 2025-10-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_season_historicalattendance_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='bonus_approved',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='bonus_approved',
        ),
    ]
