# Generated by Django 5.2.6 on 2025-10-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendance_bonus_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeeting',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
    ]
