# Generated by Django 5.2.5 on 2025-10-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_historicalmeeting_bonus_meeting_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceApprovalType',
            fields=[
                ('approval_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('approval_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='historicalattendance',
            name='approved',
        ),
    ]
