# Generated by Django 5.2.5 on 2025-10-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendanceapprovaltype_remove_attendance_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approval_typ',
            field=models.ForeignKey(default='unapp', on_delete=django.db.models.deletion.PROTECT, to='attendance.attendanceapprovaltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='approval_typ',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.attendanceapprovaltype'),
        ),
    ]
