# Generated by Django 5.2.7 on 2025-11-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_approval_typ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('meeting_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('meeting_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalmeeting',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='bonus',
        ),
    ]
