# Generated by Django 5.2.7 on 2025-11-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_meetingtype_remove_historicalmeeting_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeeting',
            name='meeting_typ',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.meetingtype'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_typ',
            field=models.ForeignKey(default='reg', on_delete=django.db.models.deletion.PROTECT, to='attendance.meetingtype'),
            preserve_default=False,
        ),
    ]
