# Generated by Django 5.2.9 on 2026-01-30 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_historicalmeeting_meeting_typ_meeting_meeting_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeeting',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalmeeting',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 30, 2, 18, 27, 81671, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 30, 2, 18, 32, 188708, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
