# Generated by Django 5.2.11 on 2026-03-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_historicalmeeting_ended_meeting_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeeting',
            name='private_ind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='private_ind',
            field=models.BooleanField(default=False),
        ),
    ]
