# Generated by Django 4.2 on 2023-06-30 00:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouting', '0011_alter_scoutquestion_void_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('fr_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('active', models.CharField(max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_typ_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('form_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('form_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('form_sub_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('form_sub_nm', models.CharField(max_length=255)),
                ('form_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.type')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('q_opt_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('form_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_response', to='form.formresponse')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.question')),
                ('scout_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scout_field', to='scouting.scoutfield')),
                ('scout_pit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scout_pit', to='scouting.scoutfield')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='form_sub_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.subtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='form_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.type'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.questiontype'),
        ),
        migrations.AddField(
            model_name='question',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.season'),
        ),
    ]
