# Generated by Django 4.2 on 2023-06-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_qa_id_questionanswer_question_answer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormResponse',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='form_response',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='fr_id',
            new_name='response_id',
        ),
    ]
