# Generated by Django 4.2 on 2023-07-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0011_alter_scoutquestion_void_ind'),
        ('form', '0004_rename_formresponse_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='form_typ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='form.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='void_ind',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='scout_pit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scout_pit', to='scouting.scoutpit'),
        ),
    ]
