# Generated by Django 4.2 on 2023-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_response_form_typ_response_void_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
