# Generated by Django 4.2 on 2023-07-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_formsubtype_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='is_list',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
