# Generated by Django 4.2 on 2023-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.CharField(default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='active',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
