# Generated by Django 4.2 on 2024-02-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_question_active_alter_questionoption_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='season',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='scout_field',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='scout_pit',
        ),
    ]
