# Generated by Django 4.2 on 2024-02-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_questionaggregatetype_questioncondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaggregate',
            old_name='question',
            new_name='questions',
        ),
    ]
