# Generated by Django 4.2 on 2024-02-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_questioncondition_condition_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncondition',
            name='condition_question',
        ),
        migrations.RemoveField(
            model_name='questioncondition',
            name='question',
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='question_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_from', to='form.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncondition',
            name='question_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_to', to='form.question'),
            preserve_default=False,
        ),
    ]
