# Generated by Django 5.1.1 on 2024-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_historicalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='archive_ind',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='response',
            name='archive_ind',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
