# Generated by Django 5.1.1 on 2024-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_question_table_col_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
