# Generated by Django 5.1.1 on 2024-12-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_question_img_id_question_img_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='requires_img',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
