# Generated by Django 5.1.1 on 2025-01-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_questionflow_remove_question_img_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionflow',
            name='form_sub_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.formsubtype'),
        ),
        migrations.AddField(
            model_name='questionflow',
            name='form_typ',
            field=models.ForeignKey(default='field', on_delete=django.db.models.deletion.PROTECT, to='form.formtype'),
            preserve_default=False,
        ),
    ]
