# Generated by Django 5.1.1 on 2025-01-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_questioncondition_question_condition_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GraphQuestionType',
            fields=[
                ('graph_question_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('graph_question_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('graph_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('graph_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GraphQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graph')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.question')),
                ('graph_question_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graphquestiontype')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='graph_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graphtype'),
        ),
    ]
