# Generated by Django 5.1.1 on 2025-01-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_graph_graphquestiontype_graphtype_graphquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphquestiontype',
            name='question_type',
            field=models.ManyToManyField(to='form.questiontype'),
        ),
    ]
