# Generated by Django 5.1.1 on 2025-01-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_graphquestiontype_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphquestiontype',
            old_name='question_type',
            new_name='question_typ',
        ),
    ]
