# Generated by Django 5.1.5 on 2025-01-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_rename_question_type_graphquestiontype_question_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFlowCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question_flow_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_flow_from', to='form.questionflow')),
                ('question_flow_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_flow_to', to='form.questionflow')),
            ],
        ),
    ]
