# Generated by Django 5.1.5 on 2025-01-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_questionflowcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_flow',
        ),
        migrations.AddField(
            model_name='question',
            name='question_flow',
            field=models.ManyToManyField(to='form.questionflow'),
        ),
    ]
