# Generated by Django 5.1.5 on 2025-01-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_remove_question_question_flow_question_question_flow'),
        ('scouting', '0042_questionflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_flow',
        ),
        migrations.RenameModel(
            old_name='QuestionFlow',
            new_name='Flow',
        ),
        migrations.CreateModel(
            name='FlowCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('flow_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_flow_from', to='form.flow')),
                ('flow_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_question_flow_to', to='form.flow')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionFlowCondition',
        ),
    ]
