# Generated by Django 5.1.5 on 2025-01-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_remove_question_question_flow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.flow')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.question')),
            ],
        ),
    ]
