# Generated by Django 5.1.5 on 2025-01-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_rename_questionanswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_flow',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_answer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='flowanswer',
            old_name='answer',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='flowanswer',
            old_name='answer_time',
            new_name='value_time',
        ),
    ]
