# Generated by Django 5.1.5 on 2025-01-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_rename_question_flow_answer_flow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowanswer',
            old_name='question_answer',
            new_name='answer',
        ),
    ]
