# Generated by Django 5.1.5 on 2025-02-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0044_rename_questionflow_flowquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaggregate',
            old_name='question_aggregate_id',
            new_name='id',
        ),
    ]
