# Generated by Django 5.1.5 on 2025-02-03 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0045_rename_question_aggregate_id_questionaggregate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='scale',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphquestion',
            name='question_aggregate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.questionaggregate'),
        ),
        migrations.AddField(
            model_name='graphtype',
            name='requires_bins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphtype',
            name='requires_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphquestion',
            name='graph_question_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.graphquestiontype'),
        ),
        migrations.AlterField(
            model_name='graphquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.question'),
        ),
        migrations.CreateModel(
            name='GraphBins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bin', models.IntegerField()),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graph')),
            ],
        ),
        migrations.CreateModel(
            name='GraphCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=2000)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graph')),
            ],
        ),
        migrations.CreateModel(
            name='GraphCategoryAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1000)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('graph_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graphcategory')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.question')),
                ('question_aggregate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.questionaggregate')),
                ('question_condition_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.questionconditiontype')),
            ],
        ),
    ]
