# Generated by Django 5.1.5 on 2025-02-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_rename_scale_graph_scale_x_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphBins',
            new_name='GraphBin',
        ),
    ]
