# Generated by Django 5.1.5 on 2025-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_rename_graphbins_graphbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphbin',
            name='width',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
