# Generated by Django 5.1.5 on 2025-02-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0055_delete_usergraphdashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='scale_x',
            new_name='x_scale_max',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='scale_y',
            new_name='x_scale_min',
        ),
        migrations.AddField(
            model_name='graph',
            name='y_scale_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='y_scale_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
