# Generated by Django 5.1.5 on 2025-02-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0056_rename_scale_x_graph_x_scale_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaggregate',
            name='question_condition_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.questionconditiontype'),
        ),
    ]
