# Generated by Django 5.1.5 on 2025-02-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0057_questionaggregate_question_condition_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaggregate',
            name='question_condition_typ',
        ),
        migrations.RemoveField(
            model_name='questionaggregate',
            name='questions',
        ),
        migrations.CreateModel(
            name='QuestionAggregateQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.question')),
                ('question_aggregate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.questionaggregate')),
                ('question_condition_typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.questionconditiontype')),
            ],
        ),
    ]
