# Generated by Django 5.1.5 on 2025-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0060_questionaggregatequestion_use_answer_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaggregatequestion',
            name='use_answer_time',
        ),
        migrations.AddField(
            model_name='questionaggregate',
            name='use_answer_time',
            field=models.BooleanField(default=False),
        ),
    ]
