# Generated by Django 5.1.5 on 2025-03-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0061_remove_questionaggregatequestion_use_answer_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaggregatequestion',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
