# Generated by Django 5.2.5 on 2025-09-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0062_questionaggregatequestion_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalresponse',
            old_name='response_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='id',
        ),
    ]
