# Generated by Django 5.2.9 on 2026-02-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0063_rename_response_id_historicalresponse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowquestion',
            name='press_to_continue',
            field=models.BooleanField(default=False),
        ),
    ]
