# Generated by Django 5.2.11 on 2026-03-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0064_flowquestion_press_to_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='form_based',
            field=models.BooleanField(default=False),
        ),
    ]
