# Generated by Django 4.2 on 2023-07-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0002_historicalitem_active_historicalitem_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
