# Generated by Django 4.2 on 2023-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0003_historicalitem_img_id_historicalitem_img_ver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsponsor',
            name='void_ind',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
