# Generated by Django 3.2.5 on 2021-07-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_nm', models.CharField(max_length=255)),
                ('date_st', models.DateTimeField()),
                ('event_cd', models.CharField(max_length=10, unique=True)),
                ('date_end', models.DateTimeField()),
                ('current', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_typ_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutField',
            fields=[
                ('scout_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPit',
            fields=[
                ('scout_pit_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(blank=True, max_length=500, null=True)),
                ('img_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutQuestionType',
            fields=[
                ('sq_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sq_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=45)),
                ('current', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.IntegerField(primary_key=True, serialize=False)),
                ('team_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutSchedule',
            fields=[
                ('scout_sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notified', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('sq_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutQuestion',
            fields=[
                ('sq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('active', models.CharField(max_length=1)),
                ('void_ind', models.CharField(max_length=1)),
                ('question_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.questiontype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.season')),
                ('sq_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPitAnswer',
            fields=[
                ('spa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('scout_pit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutpit')),
                ('sq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestion')),
            ],
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='team_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team'),
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScoutFieldAnswer',
            fields=[
                ('sfa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('scout_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutfield')),
                ('sq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestion')),
            ],
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='team_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.team'),
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScoutAuthGroups',
            fields=[
                ('scout_group', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('auth_group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('q_opt_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('sq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestion')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.season'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_no',
            field=models.ManyToManyField(to='api.Team'),
        ),
    ]
