# Generated by Django 4.0.1 on 2022-03-09 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='blue_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_one_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='blue_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_three_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='blue_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_two_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='red_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_one_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='red_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_three_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoutfieldschedule',
            name='red_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_two_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
