# Generated by Django 4.0.1 on 2022-03-09 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_scoutfieldschedule_blue_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoutpitschedule',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.event'),
            preserve_default=False,
        ),
    ]
