# Generated by Django 4.0.1 on 2022-03-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scoutfieldschedule_event_scoutpitschedule_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_number', models.IntegerField()),
                ('red_score', models.IntegerField(null=True)),
                ('blue_score', models.IntegerField(null=True)),
                ('comp_level', models.CharField(max_length=25)),
                ('time', models.DateTimeField()),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('blue_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_one_team', to='api.team')),
                ('blue_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_three_team', to='api.team')),
                ('blue_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_two_team', to='api.team')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event')),
                ('red_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_one_team', to='api.team')),
                ('red_three', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_three_team', to='api.team')),
                ('red_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_two_team', to='api.team')),
            ],
        ),
    ]
