# Generated by Django 4.0.1 on 2022-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='competition_page_active',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
