# Generated by Django 4.0.1 on 2022-03-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_address_event_event_url_event_gmaps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='webcast_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
