# Generated by Django 4.0.1 on 2022-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_state_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_st',
            field=models.DateField(),
        ),
    ]
