# Generated by Django 4.0.1 on 2022-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_date_end_alter_event_date_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
