# Generated by Django 4.0.1 on 2022-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('comp_lvl_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comp_lvl_typ_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
    ]
