# Generated by Django 4.0.1 on 2022-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_competitionlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionlevel',
            name='comp_lvl_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
