# Generated by Django 4.0.1 on 2022-03-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_competitionlevel_comp_lvl_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='comp_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.competitionlevel'),
        ),
    ]
