# Generated by Django 4.0.1 on 2022-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_match_comp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
