# Generated by Django 4.0.1 on 2022-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_key',
            field=models.CharField(default='none', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='competition_page_active',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
