# Generated by Django 4.0.1 on 2022-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_match_match_key_alter_event_competition_page_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_key',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
