# Generated by Django 4.0.1 on 2022-03-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_match_match_key_alter_match_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutQuestionSubType',
            fields=[
                ('sq_sub_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sq_sub_nm', models.CharField(max_length=255)),
                ('sq_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestiontype')),
            ],
        ),
    ]
