# Generated by Django 4.0.1 on 2022-03-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_scoutquestionsubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutquestion',
            name='sq_sub_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.scoutquestionsubtype'),
        ),
    ]
