# Generated by Django 4.0.1 on 2022-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scoutquestion_sq_sub_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
