# Generated by Django 4.0.3 on 2022-04-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('comp_lvl_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comp_lvl_typ_nm', models.CharField(max_length=255)),
                ('comp_lvl_order', models.IntegerField()),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_nm', models.CharField(max_length=255)),
                ('date_st', models.DateTimeField()),
                ('event_cd', models.CharField(max_length=10, unique=True)),
                ('event_url', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state_prov', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255, null=True)),
                ('location_name', models.CharField(max_length=255, null=True)),
                ('gmaps_url', models.CharField(max_length=255, null=True)),
                ('webcast_url', models.CharField(max_length=255, null=True)),
                ('date_end', models.DateTimeField()),
                ('timezone', models.CharField(max_length=255, null=True)),
                ('current', models.CharField(default='n', max_length=1)),
                ('competition_page_active', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('match_number', models.IntegerField()),
                ('red_score', models.IntegerField(null=True)),
                ('blue_score', models.IntegerField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('q_opt_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_typ_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutAuthGroups',
            fields=[
                ('scout_group', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutField',
            fields=[
                ('scout_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutFieldAnswer',
            fields=[
                ('sfa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutFieldSchedule',
            fields=[
                ('scout_field_sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notified', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPit',
            fields=[
                ('scout_pit_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(blank=True, max_length=500, null=True)),
                ('img_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPitAnswer',
            fields=[
                ('spa_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutQuestionType',
            fields=[
                ('sq_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sq_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=45)),
                ('current', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.IntegerField(primary_key=True, serialize=False)),
                ('team_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutQuestionSubType',
            fields=[
                ('sq_sub_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sq_sub_nm', models.CharField(max_length=255)),
                ('sq_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutQuestion',
            fields=[
                ('sq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('active', models.CharField(max_length=1)),
                ('void_ind', models.CharField(max_length=1)),
                ('question_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.questiontype')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scouting.season')),
                ('sq_sub_typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestionsubtype')),
                ('sq_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPitSchedule',
            fields=[
                ('scout_pit_sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notified', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event')),
            ],
        ),
    ]
