# Generated by Django 4.0.3 on 2022-04-06 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scouting', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutpitschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutpitanswer',
            name='scout_pit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutpit'),
        ),
        migrations.AddField(
            model_name='scoutpitanswer',
            name='sq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestion'),
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event'),
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='team_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.team'),
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_one_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_three_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_two_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event'),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_one_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_three_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_two_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutfieldanswer',
            name='scout_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutfield'),
        ),
        migrations.AddField(
            model_name='scoutfieldanswer',
            name='sq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestion'),
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event'),
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='team_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.team'),
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoutauthgroups',
            name='auth_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='sq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.scoutquestion'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_one_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_three_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blue_two_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='comp_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.competitionlevel'),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_one_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_three_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='red_two_team', to='scouting.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.season'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_no',
            field=models.ManyToManyField(to='scouting.team'),
        ),
    ]
