# Generated by Django 4.0.3 on 2023-03-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0004_schedule_and_event_team_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventteaminfo',
            old_name='event_id',
            new_name='event',
        ),
    ]
