# Generated by Django 4.0.3 on 2023-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0007_scoutfield_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
