# Generated by Django 4.2 on 2024-02-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0012_remove_scoutfieldanswer_scout_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_one_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_three_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='blue_two_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_one_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_three_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scoutfieldschedule',
            name='red_two_check_in',
            field=models.DateTimeField(null=True),
        ),
    ]
