# Generated by Django 4.2 on 2024-02-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0014_scoutfield_response_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='season',
            new_name='season_id',
        ),
        migrations.RenameField(
            model_name='scoutfield',
            old_name='response',
            new_name='response_id',
        ),
    ]
