# Generated by Django 4.2 on 2024-02-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0016_rename_season_id_question_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_id',
        ),
    ]
