# Generated by Django 4.2 on 2024-02-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0020_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id_tmp',
        ),
        migrations.RemoveField(
            model_name='scoutfield',
            name='response_id_tmp',
        ),
        migrations.RemoveField(
            model_name='scoutpit',
            name='response_id_tmp',
        ),
    ]
