# Generated by Django 5.0.3 on 2024-03-04 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scouting", "0024_scoutpitimage_void_ind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("under_review", models.BooleanField(default=False)),
                ("void_ind", models.CharField(default="n", max_length=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
