# Generated by Django 5.1.1 on 2024-12-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_question_table_col_width'),
        ('scouting', '0028_question_value_multiplier_questionvaluemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1000)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question_opt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_question_option', to='form.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scorable', models.CharField(default='n', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_question_yupe', to='form.questiontype')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionValueMap',
        ),
    ]
