# Generated by Django 5.1.1 on 2024-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0030_remove_questionoption_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
