# Generated by Django 5.1.1 on 2024-12-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0031_delete_questionoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='scorable',
        ),
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='y',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(blank=True, max_length=500, null=True)),
                ('img_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('inv_img_id', models.CharField(blank=True, max_length=500, null=True)),
                ('inv_img_ver', models.CharField(blank=True, max_length=500, null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.season')),
            ],
        ),
    ]
