# Generated by Django 5.1.1 on 2025-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0033_alter_question_height_alter_question_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon_only',
            field=models.BooleanField(default=False),
        ),
    ]
