# Generated by Django 5.1.1 on 2025-01-20 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0034_question_icon_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy', models.TextField()),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
