# Generated by Django 5.1.1 on 2025-01-20 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0035_matchstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstrategy',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
