# Generated by Django 5.1.1 on 2025-01-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0039_allianceselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldform',
            name='full_img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fieldform',
            name='full_img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
