# Generated by Django 5.1.5 on 2025-01-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0042_questionflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventteaminfo',
            old_name='team_no',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='fieldresponse',
            old_name='team_no',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='pitresponse',
            old_name='team_no',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teamnote',
            old_name='team_no',
            new_name='team',
        ),
        migrations.AlterUniqueTogether(
            name='eventteaminfo',
            unique_together={('event', 'team')},
        ),
    ]
