# Generated by Django 5.1.5 on 2025-01-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0048_rename_scout_pit_img_id_pitimage_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoutauthgroup',
            old_name='auth_group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='scoutauthgroup',
            old_name='scout_group',
            new_name='id',
        ),
    ]
