# Generated by Django 5.1.5 on 2025-01-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0051_rename_sch_id_schedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match_key',
        ),
    ]
