# Generated by Django 5.1.5 on 2025-01-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0053_rename_question_flow_questionflow_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='height',
        ),
        migrations.RemoveField(
            model_name='question',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='question',
            name='icon_only',
        ),
        migrations.RemoveField(
            model_name='question',
            name='value_multiplier',
        ),
        migrations.RemoveField(
            model_name='question',
            name='width',
        ),
        migrations.RemoveField(
            model_name='question',
            name='x',
        ),
        migrations.RemoveField(
            model_name='question',
            name='y',
        ),
    ]
