# Generated by Django 5.1.5 on 2025-02-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0057_pitimage_img_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
