# Generated by Django 5.1.5 on 2025-02-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_rename_graphbins_graphbin'),
        ('scouting', '0058_delete_questiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_graph', to='form.graph')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.season')),
            ],
        ),
    ]
