# Generated by Django 5.1.5 on 2025-02-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0062_alter_dashboardgraph_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardactiveteam',
            name='reference_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_team', to='scouting.team'),
        ),
    ]
