# Generated by Django 4.2 on 2023-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0005_itemsponsor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsponsor',
            name='can_send_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='can_send_emails',
            field=models.BooleanField(default=False),
        ),
    ]
