# Generated by Django 5.1.1 on 2024-11-29 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(blank=True, max_length=4000, null=True)),
                ('message_data', models.CharField(blank=True, max_length=4000, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
    ]
