# Generated by Django 5.1.1 on 2024-11-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processed',
            field=models.CharField(default='n', max_length=1),
        ),
    ]
