# Generated by Django 4.2 on 2023-05-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_subject', models.CharField(max_length=255)),
                ('alert_body', models.CharField(max_length=4000)),
                ('staged_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertCommunicationChannelType',
            fields=[
                ('alert_comm_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alert_comm_nm', models.CharField(max_length=255)),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AlertChannelSend',
            fields=[
                ('alert_channel_send_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_time', models.DateTimeField(null=True)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('alert_comm_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.alertcommunicationchanneltype')),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alerts.alert')),
            ],
        ),
    ]
