# Generated by Django 4.2 on 2023-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alert_id_alertchannelsend_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannelsend',
            name='dismissed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
