# Generated by Django 5.1.1 on 2025-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertchannelsend_dismissed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannelsend',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
