# Generated by Django 5.1.1 on 2025-01-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertchannelsend_tries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertChannelSend',
            new_name='ChannelSend',
        ),
        migrations.RenameModel(
            old_name='AlertCommunicationChannelType',
            new_name='CommunicationChannelType',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='communicationchanneltype',
            old_name='alert_comm_nm',
            new_name='comm_nm',
        ),
        migrations.RenameField(
            model_name='communicationchanneltype',
            old_name='alert_comm_typ',
            new_name='comm_typ',
        ),
    ]
