# Generated by Django 5.2.5 on 2025-09-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_rename_alert_comm_typ_channelsend_comm_typ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('alert_typ', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('alert_typ_nm', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=4000)),
                ('last_run', models.DateTimeField()),
                ('void_ind', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.alerttype'),
        ),
    ]
