# Generated by Django 5.2.5 on 2025-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alerttype_alert_url_alert_alert_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='body',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
