# Generated by Django 5.2.12 on 2026-06-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertedresource'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttype',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
    ]
