# Generated by Django 5.2.12 on 2026-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alerttype_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttype',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
    ]
