# Generated by Django 5.2.6 on 2025-10-25 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alerttype_body_alter_alerttype_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertedResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foreign_id', models.CharField(verbose_name=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('alert_typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alerts.alerttype')),
            ],
        ),
    ]
