# Generated by Django 5.2.7 on 2025-10-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertedresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertedresource',
            name='foreign_id',
            field=models.CharField(max_length=2000),
        ),
    ]
