# Generated by Django 5.2.15 on 2026-10-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='on_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='on_loan',
            field=models.BooleanField(default=False),
        ),
    ]
