# Generated by Django 5.0.3 on 2024-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='traceback',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
