# Generated by Django 4.0.3 on 2023-03-19 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_alter_eventteaminfo_dq_alter_eventteaminfo_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutfield',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
