# Generated by Django 4.2.5 on 2023-09-20 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scouting", "0011_alter_scoutquestion_void_ind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoutfieldanswer",
            name="scout_field",
        ),
        migrations.RemoveField(
            model_name="scoutfieldanswer",
            name="sq",
        ),
        migrations.RemoveField(
            model_name="scoutpitanswer",
            name="scout_pit",
        ),
        migrations.RemoveField(
            model_name="scoutpitanswer",
            name="sq",
        ),
        migrations.RemoveField(
            model_name="scoutquestion",
            name="question_typ",
        ),
        migrations.RemoveField(
            model_name="scoutquestion",
            name="season",
        ),
        migrations.RemoveField(
            model_name="scoutquestion",
            name="sq_sub_typ",
        ),
        migrations.RemoveField(
            model_name="scoutquestion",
            name="sq_typ",
        ),
        migrations.RemoveField(
            model_name="scoutquestionsubtype",
            name="sq_typ",
        ),
        migrations.DeleteModel(
            name="QuestionOptions",
        ),
        migrations.DeleteModel(
            name="QuestionType",
        ),
        migrations.DeleteModel(
            name="ScoutFieldAnswer",
        ),
        migrations.DeleteModel(
            name="ScoutPitAnswer",
        ),
        migrations.DeleteModel(
            name="ScoutQuestion",
        ),
        migrations.DeleteModel(
            name="ScoutQuestionSubType",
        ),
        migrations.DeleteModel(
            name="ScoutQuestionType",
        ),
    ]
