# Generated by Django 4.2 on 2024-02-05 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0013_scoutfieldschedule_blue_one_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutfield',
            name='response',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(null=True)),
                ('scorable', models.BooleanField(default=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scouting_question_season', to='scouting.season')),
            ],
        ),
    ]
