# Generated by Django 4.2 on 2024-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0015_rename_season_question_season_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='season_id',
            new_name='season',
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='response_id',
            field=models.IntegerField(null=True),
        ),
    ]
