# Generated by Django 4.2.5 on 2024-02-07 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scouting", "0017_rename_question_question_question_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question_id",
            new_name="question_id_tmp",
        ),
        migrations.RenameField(
            model_name="scoutfield",
            old_name="response_id",
            new_name="response_id_tmp",
        ),
        migrations.RenameField(
            model_name="scoutpit",
            old_name="response_id",
            new_name="response_id_tmp",
        ),
    ]
