# Generated by Django 4.2 on 2024-02-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_remove_question_season_and_more'),
        ('scouting', '0018_rename_question_id_question_question_id_tmp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='form_question', to='form.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoutfield',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.response'),
        ),
        migrations.AddField(
            model_name='scoutpit',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form.response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.season'),
        ),
    ]
