# Generated by Django 4.2 on 2024-02-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_remove_question_season_and_more'),
        ('scouting', '0019_question_question_scoutfield_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_question', to='form.question'),
        ),
    ]
