# Generated by Django 5.1.1 on 2024-11-30 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0027_rename_team_no_event_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value_multiplier',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='QuestionValueMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
                ('default', models.CharField(default='n', max_length=1)),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_value_map', to='scouting.question')),
            ],
        ),
    ]
