# Generated by Django 5.1.1 on 2024-12-02 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_question_table_col_width'),
        ('scouting', '0029_questionoption_questiontype_delete_questionvaluemap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='active',
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='question_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_question_type', to='form.questiontype'),
        ),
    ]
