# Generated by Django 5.1.1 on 2025-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0032_remove_question_scorable_question_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
