# Generated by Django 5.1.1 on 2025-01-20 04:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0036_matchstrategy_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamNotes',
            new_name='TeamNote',
        ),
    ]
