# Generated by Django 5.1.1 on 2025-01-20 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('form', '0033_rename_question_type_graphquestiontype_question_typ'),
        ('scouting', '0037_rename_teamnotes_teamnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoutField',
            new_name='FieldResponse',
        ),
        migrations.RenameModel(
            old_name='ScoutFieldSchedule',
            new_name='FieldSchedule',
        ),
        migrations.RenameModel(
            old_name='ScoutPitImage',
            new_name='PitImage',
        ),
        migrations.RenameModel(
            old_name='ScoutPit',
            new_name='PitResponse',
        ),
        migrations.RenameModel(
            old_name='ScoutAuthGroups',
            new_name='ScoutAuthGroup',
        ),
    ]
