# Generated by Django 5.1.1 on 2025-01-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0038_rename_scoutfield_fieldresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('order', models.IntegerField()),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.team')),
            ],
        ),
    ]
