# Generated by Django 5.1.1 on 2025-01-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0040_fieldform_full_img_id_fieldform_full_img_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstrategy',
            name='img_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='matchstrategy',
            name='img_ver',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
