# Generated by Django 5.1.5 on 2025-01-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_remove_question_question_flow_question_question_flow'),
        ('scouting', '0041_matchstrategy_img_id_matchstrategy_img_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('question_flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout_question_flow', to='form.questionflow')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.season')),
            ],
        ),
    ]
