# Generated by Django 5.1.5 on 2025-01-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0043_rename_team_no_eventteaminfo_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_id',
            new_name='id',
        ),
    ]
