# Generated by Django 5.1.5 on 2025-01-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0044_rename_event_id_event_id_rename_season_id_season_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamnote',
            old_name='team_note_id',
            new_name='id',
        ),
    ]
