# Generated by Django 5.1.5 on 2025-01-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0045_rename_team_note_id_teamnote_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldresponse',
            old_name='scout_field_id',
            new_name='id',
        ),
    ]
