# Generated by Django 5.1.5 on 2025-01-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0046_rename_scout_field_id_fieldresponse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitresponse',
            old_name='scout_pit_id',
            new_name='id',
        ),
    ]
