# Generated by Django 5.1.5 on 2025-01-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0047_rename_scout_pit_id_pitresponse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitimage',
            old_name='scout_pit_img_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pitimage',
            old_name='scout_pit',
            new_name='pit_response',
        ),
    ]
