# Generated by Django 5.1.5 on 2025-01-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0049_rename_auth_group_id_scoutauthgroup_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldschedule',
            old_name='scout_field_sch_id',
            new_name='id',
        ),
    ]
