# Generated by Django 5.1.5 on 2025-01-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0050_rename_scout_field_sch_id_fieldschedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='sch_id',
            new_name='id',
        ),
    ]
