# Generated by Django 5.1.5 on 2025-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0052_rename_match_id_match_match_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionflow',
            old_name='question_flow',
            new_name='flow',
        ),
    ]
