# Generated by Django 5.1.5 on 2025-02-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0054_remove_question_height_remove_question_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitImageType',
            fields=[
                ('pit_image_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pit_image_nm', models.CharField(max_length=255)),
            ],
        ),
    ]
