# Generated by Django 5.1.5 on 2025-02-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0055_pitimagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitimage',
            name='pit_image_typ',
            field=models.ForeignKey(default='robot-img', on_delete=django.db.models.deletion.PROTECT, to='scouting.pitimagetype'),
            preserve_default=False,
        ),
    ]
