# Generated by Django 5.1.5 on 2025-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0056_pitimage_pit_image_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitimage',
            name='img_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
