# Generated by Django 5.1.5 on 2025-02-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0060_dashboard_dashboardgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardActiveTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_team', to='scouting.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.team')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='active_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.dashboardactiveteam'),
        ),
    ]
