# Generated by Django 5.1.5 on 2025-02-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0055_delete_usergraphdashboard'),
        ('scouting', '0061_dashboardactiveteam_dashboard_active_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardgraph',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.graph'),
        ),
    ]
