# Generated by Django 5.1.5 on 2025-02-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0063_alter_dashboardactiveteam_reference_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardactiveteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scouting.team'),
        ),
    ]
