# Generated by Django 5.1.5 on 2025-02-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0066_remove_dashboard_team_dashboard_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardViewType',
            fields=[
                ('dash_view_typ', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dash_view_nm', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='reference_team',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='dashboardgraph',
            name='dashboard',
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('order', models.IntegerField()),
                ('active', models.CharField(default='y', max_length=1)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.dashboard')),
                ('reference_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_team', to='scouting.team')),
                ('teams', models.ManyToManyField(to='scouting.team')),
                ('dash_view_typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.dashboardviewtype')),
            ],
        ),
    ]
