# Generated by Django 5.2.5 on 2025-08-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0069_userinfo_eliminate_results_userinfo_group_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='game',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='manual',
            field=models.CharField(default=' ', max_length=2000),
            preserve_default=False,
        ),
    ]
