# Generated by Django 5.2.11 on 2026-06-15 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0070_season_game_season_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('void_ind', models.CharField(default='n', max_length=1)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scouting.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scouting_user_season', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
