# Generated by Django 5.1.5 on 2025-01-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_link_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_id',
            new_name='id',
        ),
    ]
