# Generated by Django 5.1.5 on 2025-01-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_link_id_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonetype',
            old_name='phone_type_id',
            new_name='id',
        ),
    ]
