# Generated by Django 5.2.6 on 2025-10-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_meeting_rename_time_attendance_time_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeeting",
            name="description",
            field=models.CharField(default="", verbose_name=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmeeting",
            name="title",
            field=models.CharField(default="", verbose_name=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.CharField(default="", verbose_name=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="title",
            field=models.CharField(default="", verbose_name=2000),
            preserve_default=False,
        ),
    ]
