# Generated by Django 5.2.6 on 2025-10-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendance_absent_historicalattendance_absent"),
        ("scouting", "0070_season_game_season_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeeting",
            name="season",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="scouting.season",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="season",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                to="scouting.season",
            ),
            preserve_default=False,
        ),
    ]
