# Generated by Django 5.2.6 on 2025-10-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_historicalmeeting_season_meeting_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
