# Generated by Django 5.2.7 on 2025-10-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_approval_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeeting',
            name='description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='historicalmeeting',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
